okx_key: ...
okx_secret: ...
okx_password: ...

shuffle: true  # Размешивать кошельки?
symbol: "ETH"  # Какие токены: ETH, USDC, USDT ...
network: "Arbitrum One"  # Какие сети? ERC20, Arbitrum One, zkSync Lite, Optimism, Starknet, zkSync Era, Linea, Base
amount_withdraw: [0.004, 0.005]  # Сумма вывода
sleep_after_withdraw: [60, 90] # Сколько ждем после вывода?

