okx_key: ...
okx_secret: ...
okx_password: ...

filename: wallets.txt

shuffle: true  # Размешивать кошельки?
symbol: "ETH"  # Какие токены: ETH, USDC, USDT ...
network: "zkSync Era"  # Какие сети? ERC20, Arbitrum One, zkSync Lite, Optimism, Starknet, zkSync Era, Linea, Base
amount_withdraw: [0.00081, 0.00105]  # Сумма вывода
withdraw_fee: 0.0001  # в случае если ошибка при получении комиссии
sleep_after_withdraw: [144, 867] # Сколько ждем после вывода?
